image: docker:latest

services:
- docker:dind

build-api:
  stage: build
  script:
  - cd Navtrack.Api
  - docker build .

build-listener:
  stage: build
  script:
  - docker build . -f Navtrack.Listener/Dockerfile
