image: docker:latest

services:
  - docker:dind

before_script:
  - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin

build-api:
  stage: build
  script:
  - cd Navtrack.Api
  - docker build . -t navtrack/api
  - docker push navtrack/api

build-listener:
  stage: build
  script:
  - docker build . -f Navtrack.Listener/Dockerfile -t navtrack/listener
  - docker push navtrack/listener

deploy:
  stage: deploy
  before_script:
  - 'which ssh-agent || ( apk update -y && apk add openssh-client -y )'
  script:
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - echo "$DEPLOY_SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - eval $(ssh-agent -s)
  - echo "$DEPLOY_SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - ssh $DEPLOY_SSH_USER@$DEPLOY_HOST "cd $DEPLOY_FOLDER && docker-compose pull && docker-compose up -d"