image: docker:latest

services:
  - docker:dind

before_script:
  - docker login -u $CI_REGISTRY_USER -p "$CI_REGISTRY_PASSWORD"

build-api:
  stage: build
  script:
  - cd Navtrack.Api
  - docker build . -t navtrack/api
  - docker push navtrack/api

build-listener:
  stage: build
  script:
  - docker build . -f Navtrack.Listener/Dockerfile -t navtrack/listener
  - docker push navtrack/listener