version: '3.4'

services:
  web:
    image: docker.pkg.github.com/navtrack/navtrack/web:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    env_file:
      - .env_navtrack

  listener:
    image: docker.pkg.github.com/navtrack/navtrack/listener:latest
    ports:
      - 6801:6801
      - 6802:6802
    restart: always
    env_file:
      - .env_navtrack
