name: CI

on: [push]

jobs:
  build-check:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build solution
      run: dotnet build 
    - name: Test solution
      run: dotnet test