name: Build check

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build solution
      run: dotnet build 
      
  test:
    runs-on: windows-latest
    steps:
    - name: Test solution
      run: dotnet test
