name: Git sync

on:
  push:
    branches:
      - main

jobs:
  git-sync:
    if: github.repository == 'navtrack/navtrack'
    runs-on: ubuntu-latest
    steps:
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "navtrack/navtrack"
          source_branch: "main"
          destination_repo: "navtrack/navtrack-internal"
          destination_branch: "main-public"
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }}
