name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Test the solution
      run: docker build -f Navtrack.Listener.Tests/Dockerfile .
